### ISSUE TITLE
Add option to explicitly turn off default mappings

### ISSUE THREAD

**Issue by perrin4869** [inkarkat/vim-ReplaceWithRegister#1]
Thanks for taking over maintenance of this plugin, and adding tests, etc :)
I like setting my mappings in an `after` script (this is necessary in the case of some plugins).
It would be useful to add an option such as `g:ReplaceWithRegisterDefaultMappings` to control whether or not to map `gr` to `<Plug>ReplaceWithRegisterOperator`.

**Comment by perrin4869** [comment]
Migrated to `vim-substitute` so kind of lost interest in this one

**Comment by inkarkat** [comment]
The default mappings can be disabled (individually) by mapping a dummy mapping to them:

    nmap <Plug>DisableReplaceWithRegisterOperator <Plug>ReplaceWithRegisterOperator
    nmap <Plug>DisableReplaceWithRegisterLine     <Plug>ReplaceWithRegisterLine
    xmap <Plug>DisableReplaceWithRegisterVisual   <Plug>ReplaceWithRegisterVisual

Some plugins offer a configuration variable to turn off all default mappings, but as this plugin only offers three mappings, I think that's not worth it here.
