### ISSUE TITLE
Does not work with empty parentheses.

### ISSUE THREAD

**Issue by kuator** [inkarkat/vim-ReplaceWithRegister#3]
It would be nice if the plugin could paste text into empty parentheses.

**Comment by inkarkat** [comment]
You can do normal `p` / `P` if there's no text to replace (as inside empty parentheses) - the plugin is not needed for that. Also, at least for me, `gri(` works just fine.

**Comment by kuator** [comment]
I'm sorry to post on the closed issued, I didn't clarify that I use targets.vim and it chooses nearest parentheses on the current line.
