### ISSUE TITLE
bug with html tag

### ISSUE THREAD

**Issue by sawogus29** [inkarkat/vim-ReplaceWithRegister#4]
**Describe the bug**

When html tag itself (like \<div\>) and it's inner text is divided by line,
the closing angle bracket '>' of leading tag gets deleted.
(see the second picture below)

**How to Reproduce**
1. yiw     at line 1
![image](https://user-images.githubusercontent.com/37795048/123163095-4dd1f180-d4ac-11eb-9ef2-a5bd1d274dac.png)

2. grit     at line 4
![image](https://user-images.githubusercontent.com/37795048/123163189-66daa280-d4ac-11eb-9016-3dc540240248.png)

**Environment**
 - Plugin version: stable version _1.43
 - Vim version: 8.0
 - OS: ubuntu 18.04
 - Install method: Plugin manager (vim-plug)
 - no other plugin

**Comment by inkarkat** [comment]
Thanks for reporting this corner case; Vim unfortunately doesn't make it easy to implement a custom opfunc that works in all situations.
